### ISSUE TITLE
Error loading script: main.py AttributeError: module 'modules.ui_extra_networks' has no attribute 'intialize'

### ISSUE THREAD

**Issue by HeavyTony2** [guaneec/custom-diffusion-webui#11]
```
Error loading script: main.py
Traceback (most recent call last):
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\user\Documents\TestSD\stable-diffusion-webui\extensions\custom-diffusion-webui\scripts\main.py", line 32, in <module>
    ui_extra_networks_initialize_bak = ui_extra_networks.intialize
AttributeError: module 'modules.ui_extra_networks' has no attribute 'intialize'
```

**Comment by Harvester62** [comment]
As per bug tracker #10 the developer seems to be no longer maintaining this extension.
